### PR TITLE
Add setuptools and rez packaging

### PR DESCRIPTION
**Pull request by rfletchr**
This merge adds setup-tools, and rez packaging, this should make it easier for folks to integrate these tools into their own pipelines. 

@JakobJK If your interested I can extend the setuptools configuration to also push the code to pypi.

# Versioning
There are many ways to handle sharing of version numbers, for the sake of simplicity I've chosen the simplest which is putting the version number into a file `__version__.py`.

### CODE REVIEW

**Comment by JakobJK** [comment]
This is a fantastic idea. I would need to update the help URL to an actually working URL, but that's fine to update at a later stage.

@rfletchr, integration with pypi would be great! Will this be run by GitHub actions? I'll make a pypi account, and set up some Github Secrets if that's the case.

**Comment by rfletchr** [comment]
yep actions would be the way to do it, though be very careful how you expose the secret. You need to make it so that only approved people can run CI so that someone cant create a branch with custom CI and send themselves your secret. 

So far as the CI goes. There are 3 ways to trigger this
- when a pull request is merged.
- when a tag with a version number is created.
- via a manually triggered action.

**Comment by JakobJK** [comment]
Right on. That makes sense. I'm leaning towards protecting the main branch, and having the CI run on merged PRs (and only merged PRs for the main branch). It's just what I'm used to, but if you have another preference I'd love your perspective.

I'm ready to go ahead and merge this PR, and will you then open a new PR for the integration with Pypi? Let me know if that fits you. Thanks

**Comment by rfletchr** [comment]
that makes perfect sense. I'm so used to working on private repos Its rarely something I need to consider.

LGTM :)

**Pull request merged**
